Update fixup-mountpoints
Halium/hybris-boot pull request #5
Opened 2017-08-07 14:20 UTC by Elfmagi

Add oneplus3 mountpoints

2017-08-08 06:24 UTC, bhush9 requested changes

2017-08-08 06:24 UTC, bhush9 commented on fixup-mountpoints
> +            -e 's block/bootdevice/by-name/LOGO block/sde17 ' \
You don't have to `block/sde17` but just `sde17` here..

So this line becomes, e,g.
`
-e 's block/bootdevice/by-name/LOGO sde17 ' \
`

2017-08-08 14:51 UTC, Elfmagi commented
I removed extra verbage e.g block/sde17 to just sde17

2017-08-09 10:42 UTC, bhush9 approved these changes

2017-08-09 10:43 UTC, merged